FROM python:3.9 AS builder 

WORKDIR /app/backend

RUN apt update \
    && apt install -y  gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt  .

RUN pip install mysqlclient \
    && pip install -r requirements.txt

FROM python:3.9-slim 

WORKDIR /app/backend

RUN apt update \
    && apt install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

COPY . .

CMD ["./entrypoint.sh"]
