version: "3.8"

services:
  nginx:
    build:
      context: "./nginx"
    container_name: "nginx"
    ports: 
      - "80:80"
    networks: 
      - "django-app"
    restart: "always"  
    depends_on:
      - "django-app"

  mysql:
    image: "mysql"
    container_name: "mysql"
    ports:
      - "3306:3306"
    networks:
      - "django-app"
    volumes:
      - "django-app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "48159"
      MYSQL_DATABASE: "django-app"
    healthcheck:
      test: ["CMD" , "mysqladmin" , "ping",  "-h",  "localhost" , "-u", "root", "-p48159"]
      interval: "5s"
      timeout: "5s"
      retries: "5"
    restart: "always"

  django-app:
    build:
      context: "."
    container_name: "django-app"
    ports:
      - "8000:8000"
    networks:
      - "django-app"
    environment:
      DB_NAME: "django-app"
      DB_HOST: "mysql"
      DB_USER: "root"
      DB_PASSWORD: "48159"
      DB_PORT: "3306"
    depends_on: 
      mysql:
        condition: "service_healthy"
    restart: "always"

networks:
  django-app:

volumes:
  django-app:  
